README.md
Summary:
- Add a `Quickstart` section to README.md
- Fix README typos
=> Add Quickstart to README.md + fix some typos

ptr.py, ptr_tests.py
- Add a unit test for `_test_steps_runner` with no "run_black" key and ensure it does not run
Test via ptr:
```
-- Summary (total time 6s):
✅ PASS: 1
❌ FAIL: 0
⌛️ TIMEOUT: 0
💩 TOTAL: 1
-- 1 / 1 (100%) `setup.py`'s have `ptr` tests running
```
Issue: #11
=> Fix logic of when to skip a step

mypy.ini, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, setup.cfg.sample, setup.py
- Add parsing of a setup.cfg if it exists and has a ptr section
- Basically convert setup.cfg to same format as ptr_params dict
- Add test to show function works
- Increased unit test %
- Move mypy to allow for >= 3.6 features
Issue #1
=> Add support for [ptr] config in setup.cfg

azure-pipelines.yml
Summary:
- Add Mac OS X testing through azure
Test Plan:
- See CI pass
Issue: #3
=> Add Mac OS X azure Pipeline

.gitignore, ptr.py
When developing `ptr` using a virtualenv inside the git repo (eg, `ptr/.venv/`), running `ptr` ends up also running **black** on the entire contents of the virtualenv.  This adds a simple filter to `find_py_files` to ignore directories with names that start with a dot.  Also adds `.venv` to `.gitignore` to facilitate this manner of development. 
Test Plan:
- `ptr` before and after
=> Ignore dotted directories when running black

.pylint, ci.py, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, ptrconfig.sample, requirements.txt, setup.cfg.sample, setup.py
Summary:
- Adds two new run steps, one each for flake8 and pylint.
- Adds respective `run_flake8` and `run_pylint` config options.
- Adds a heavily customized `.pylint` config to the repo and fixes a few outstanding lint errors.
- Includes unit tests and updates existing tests to pass
Test Plan:
- Run `ptr` and it passes
- Introduce lint errors
- Run `ptr` and it fails with lint errors
Issue: #20
=> Add support for flake8 and pylint

ptr.py, ptr_tests.py
In the case of mypy and linters, their expected outputs are on stdout,
but in the case of fatal errors during execution, they will output on
stderr.  In order to not need to look at both, and to remove the need to
keep a list of steps that output to one or the other, this makes all
steps send stderr to stdout, and always looks at stdout.
=> Pipe all stderr to stdout

.pylint, azure-pipelines.yml, ci.py, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, setup.py
Summary:
- Fix remaining venv creation issues
- Increase timeouts for pip on Windows (so slow - need to workout why)
- Turn off type ignores so mypy will pass - Issue opened on TypeShed to see long term fix: https://github.com/python/typeshed/issues/2816
Test Plan:
Running `ptr` manually on Windows
Issue: #2
=> Enable Windows Integration Tests

.pylint, azure-pipelines.yml, ptr.py, ptr_tests.py
Summary:
- Allow ptr integration run on Windows 3.7
- We will just not run black for now until black is fixed for Python 3.7 on Windows and released to PyPI
Test Plan:
- Test new function and docstring as to why it exists
Issue: #2
=> Just disable Black on Windows 3.7 only + Enable CI

ptr.py
- Allow developer to more easily know what underlying step failed
Test Plan:
Made a type error:
```
cooper-mbp:ptr cooper$ ~/venvs/pd/bin/python ptr.py --venv ~/venvs/pd/
[2019-03-28 16:15:43,281] INFO: Starting ptr.py (ptr.py:998)
[2019-03-28 16:15:43,370] INFO: Installing /Users/cooper/repos/ptr/setup.py + deps (ptr.py:542)
[2019-03-28 16:15:45,635] INFO: Running ptr_tests tests via coverage (ptr.py:542)
[2019-03-28 16:15:49,182] INFO: Analyzing coverage report for /Users/cooper/repos/ptr/setup.py (ptr.py:542)
[2019-03-28 16:15:49,454] INFO: Running mypy for /Users/cooper/repos/ptr/setup.py (ptr.py:542)
-- Summary (total time 7s):
✅ PASS: 0
❌ FAIL: 1
⌛️ TIMEOUT: 0
💩 TOTAL: 1
-- 1 / 1 (100%) `setup.py`'s have `ptr` tests running
-- Failure Output --
/Users/cooper/repos/ptr/setup.py …
```
=> Add step_name to failure output

.gitignore, .travis.yml, ci.py, ptr.py, ptr_tests.py, requirements.txt, setup.py
- Add into a venv and check + fix errors
```
python3 -m venv /tmp/pyre
/tmp/pyre/bin/pip install -r requirements.txt
/tmp/pyre/bin/pyre --source-directory . check
```
- Ignore `setup.py`
- Testing:
```
cooper-mbp1:ptr cooper$ /tmp/pyre/bin/python3 ci.py
Using Python 3.6.2+
Running `pyre` type checking
ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
ƛ No type errors found
```
Fixes #38
=> Add pyre type checking to ptr ci

ci.py, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, setup.py
- Allow a test to be disabled so automatic discovery will ignore
- Add `--force` option to overrule the ignoring of disabled test suites
- Make tests suite disabled but use --force in CI to have them run
Fixes #46
=> Add disabled config option

ptr.py, ptr_tests.py, ptr_tests_fixtures.py, setup.py
- Make it easier to find missed `setup.(cfg|py)`
- Add unit tests
Sample Output from tests:
```
cooper-mbp1:terragraph-ansible cooper$ time /tmp/test_non_ptr_mods/bin/ptr --print-non-configured
[2019-07-16 09:08:43,483] INFO: Starting /tmp/test_non_ptr_mods/bin/ptr (ptr.py:1070)
== 8 non ptr configured modules ==
- /Users/cooper/repos/terragraph-ansible/dns_ldap_checker/setup.py
- /Users/cooper/repos/terragraph-ansible/docker_proxy/setup.py
- /Users/cooper/repos/terragraph-ansible/docker_v6up/setup.py
- /Users/cooper/repos/terragraph-ansible/esxi_ssh_monitor/setup.py
- /Users/cooper/repos/terragraph-ansible/iperfc/setup.py
- /Users/cooper/repos/terragraph-ansible/jenkins/NMS_push_e2e_controller/setup.py
- /Users/cooper/repos/terragraph-ansible/nms_ip_getter/setup.py
- …
```
=> Add `--print-non-configured` to print Non ptr enabled Python Projects

ptr.py
Summary:
- Move the parsing of the setup.py file out of `_get_test_modules` to clean up the function and remove the lint warning.
Test Plan:
- Ran `ptr_tests.py` and ensured nothing broke. 
- Ran `pylint` on `ptr.py` and verified the error was gone.
Issue: #48
=> Refactor _get_test_modules function to remove lint error.

ptr.py, ptr_tests.py
- No longer need it disabled on Windows by default
- Remove function and unittest that ensured we disabled correctly
Fixes #41
#deadCode
=> Renable black now it runs in Windows on > 3.7.2

ptr.py, ptr_tests_fixtures.py, setup.py
- Not all AST `targets` has an id
- Use `getattr` to get id if it exists otherwise set the variable to None and skip
Fixes #54
=> Fix AST pasing of setup.py to handle `targets` with no id attribute

ci.py, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, setup.py
- It seems coverage resolves /private in file paths on Mac OS X if /tmp or /var/ used for file paths
- If venv path does not match that we incorrectly error saying we can't find relative path
- Fixed all new pylint errors on ci.py ...
Test: Add tests for new fucntion
This change ensures we're MAC OS X before we do this dirty hack AND that we're not specifying using /private
=> Handle OSX /private in coverage report

.gitignore, .travis.yml, README.md, ptr.py, ptr_tests.py
Summary:
- Add a Integration run to 3.8 as we now want to support it officially
- Block on 3.8 fails
- Add a nightly so we can squash issues sooner
Test Plan:
- This is the diff to run test on my Python versions
Issue: N/A
=> [ptr] Move CI to 3.8 offical + nightly

ptr.py, ptr_tests.py
Summary:
- Add `KeyError` exception when a file is in required coverage while it doesn't exist.
Test Plan:
- Add a unit test for this specific case.
Issue: #51
=> Add better handling for file not exists while in REQ_COV

.github/workflows/pythonpackage.yml, README.md
Summary:
- Added github workflow for push and PR
- Removed azure-pipeline because the issue mentioned in #61 
- The only bummer here is that 3.8 isn't supported yet (wip [issue](https://github.com/actions/setup-python/issues/30)
Test Plan:
We might leave both Travis and Github action for a while maybe until the official release of GitHub Actions.
Issue: #61
=> Add github action/workflow

ptr.py
Summary:
- If `os.cpu_count()` is 1, `int` casting floors the atonce config param to 0. 
Test Plan:
- Ran on my lab VM. Ran ptr on default_routes service.
=> Bug fix in atonce config param

ci.py
- Since ptr has no imported dependencies we can run unit tests directly
Fixes #71
=> Remove deprecated setuptools `test` option

ptr.py, ptr_tests.py
Summary:
- Currently, prt does not proceed if `test_suite` param is not provided. This diff removes this dependancy. 
- If `test_suite` if not provided, prt will run all other specified tests (i.e black, mypy, flake8, etc), except unit tests.
Test Plan:
- Tested the unit tests using `ci.py`. Also tested manually on nms/nano's topology service. 
- Only `test_async_main` is failing. 
```
test_analyze_coverage (ptr_tests.TestPtr) ... ok
test_analyze_coverage_errors (ptr_tests.TestPtr) ... ok
test_async_main (ptr_tests.TestPtr) ... FAIL
test_config (ptr_tests.TestPtr) ... ok
test_create_venv (ptr_tests.TestPtr) ... ok
test_find_setup_py (ptr_tests.TestPtr) ... ok
test_find_setup_py_exclude_default (ptr_tests.TestPtr) ... ok
test_gen_output (ptr_tests.TestPtr) ... ok …
```
=> Run ptr even when test_suite is not provided

ptr_tests.py
- Share args to pass
- Share some expected in assertEquals
- Explicitly pass wether or not to print coverage
Also remove an unused temporary directory.
=> Cleanup some _test_steps_runner tests copy pasta + refactor

CHANGES.md, MANIFEST.in, setup.py
Fixes #76
```
cooper-mbp1:dist cooper$ tar xvzf ptr-19.11.21.tar.gz
x ptr-19.11.21/
x ptr-19.11.21/CHANGES.md
x ptr-19.11.21/LICENSE
x ptr-19.11.21/MANIFEST.in
x ptr-19.11.21/PKG-INFO
x ptr-19.11.21/README.md
x ptr-19.11.21/ptr.egg-info/
x ptr-19.11.21/ptr.egg-info/PKG-INFO
x ptr-19.11.21/ptr.egg-info/SOURCES.txt
x ptr-19.11.21/ptr.egg-info/dependency_links.txt
x ptr-19.11.21/ptr.egg-info/entry_points.txt
x ptr-19.11.21/ptr.egg-info/top_level.txt
x ptr-19.11.21/ptr.py
x ptr-19.11.21/ptr_tests.py
x ptr-19.11.21/ptr_tests_fixtures.py
x ptr-19.11.21/setup.cfg
x ptr-19.11.21/setup.py
```
=> Add LICENSE to sdist + move to 2019.11.21 + update CHANGES.md

ptr.py, ptr_tests.py
- Default ptrconfig options that aren't supplied
- Overwrite supplied options
- Also uncomment a pyre comment that's no longer needed
Fixes #79
=> Add ability to create partial .ptrconfig files

ptr.py, ptr_tests.py
- In 5.0 the ENV Var has changed to DATA_FILE rather than COVERAGE_FILE
-- https://coverage.readthedocs.io/en/coverage-5.0/config.html#run
Test: Run on my MAC and see coverage data analyzed again
Fixes #84
=> Change coverage Data File Env Var for >= 5.0

ptr.py
Summary:
- If it works, lets update pip and setuptools on Windows by default
Test Plan:
- CI runs the upgrade
Fixes #33
=> Allow Windows to update pip + setuptools

README.md, ptr.py
I accidentally messed up the order of args in the last PR. "system-site-packages" should come after "stats-file".
=> Realphabetize command line args

README.md, ptr.py, ptr_tests.py, requirements.txt
- Revert uneeded coverage 5.0 hack as we cwd into setup_py_path.parent
- 5.0.1 also fixes/better errors the bug with an old 4.x coverage file existing
=> Coverage hack uneeded

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates states that the updated template formats should include YAML front matter.
> To be included in the community profile checklist, issue templates must be located in the .github/ISSUE_TEMPLATE folder and contain valid name: and about: YAML front matter.
=> Add yaml front matter to issues templates

.github/workflows/ci.yml, .github/workflows/pypi_upload.yml, ptr_tests.py, setup.py
- Up python_requires >= 3.7
- Stop Actions running 3.6
- Update some actions versions
Python 3.6 was EOL 12/23/2021
=> Drop Python 3.6 support + CI

.github/workflows/pypi_upload.yml, pyproject.toml
- `setup.py` direct invocations is deprecated
- https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
- Lets be good and move to `build` PEP517 buld frontend that should do the right things
Test
- Show Python version used for test:
```
crl-m1:ptr cooper$ python3 -V
Python 3.9.10
```
- `/tmp/test_build/bin/pip --upgrade build pip setuptools twine wheel`
- `/tmp/test_build/bin/pip install --upgrade build pip setuptools twine wheel`
- `/tmp/test_build/bin/python -m build`
- Output: https://pastebin.com/9SDaYL15
=> Move to PEP517 `build` build frontend for packaging

.github/workflows/ci.yml, .github/workflows/ci_latest.yml, .github/workflows/fuzz.yml, README.md, ptr.py, ptr_tests.py, ptr_tests_fixtures.py, pyproject.toml, setup.py
- [tool.ptr] Section support in pyproject.toml
- Parses the toml into the same dict structure as `setup.cfg` + `setup.py` now
- `pyproject.toml` is more preferred than `setup.cfg` + `setup.py`
Test:
- Add unittest for parsing pyproject.toml
- See Integration test stay working as pyproject.toml would be preferred
- @patch mock to keep test_get_test_modules go through the if statements for coverage
Fixes #91
This does not change ptr to install using pyproject.toml yet ... just suport projects with ptr config in there.
=> Add pyproject.toml support
