facebookincubator/ptr

ci.py

- Check if stats log any fails
- Check if we don't test all `setup.py` files
- Check that we only ever have 1 `setup.py` file
Issue: #7

Add some basic stats JSON checking

---

README.md

Remove 'coming soon' re: setup.cfg - Support is merged

---

ci.py

- Azure does not run ptr in a venv
- Due to this, lets have ptr create a venv to run it's tests in :)
If Travis and Azure pass - we're good here.
Fixes #3

Add non VENV Ran CI Support

---

release_to_pypi.sh

Summary:
- Add copyright header to release_to_pypi.sh
Test Plan:
NA

[Fix] Add copyright header

---

ptr.py

When executing coverage, mypy, and linters, set the subprocess CWD to
the path containing the package's `setup.py`.  When running code
coverage, se the `-m` flag rather munging the `test_suite` config value
to run a spcific file. This will most closely match common patterns for
running and linting packages with tests modules outside of the package.
This will also enable these tools to correctly discover configuration
stored in `setup.cfg` files.
Test plan:
- `ptr -d`
- `PTR_INTEGRATION=1 python ci.py` from within venv
- Clone https://github.com/jreese/aiosqlite and run `ptr -d`
Issue: #23, #26

Fix #23: Run tests/mypy/flake in CWD of setup.py path

---

.ptrconfig
.pylint
azure-pipelines.yml
ptr.py
ptr_tests.py
ptr_tests_fixtures.py
setup.py

Let's get some CI running on Windows.
- Remove .ptrconfig symlink
- Set encoding in setup.py to utf-8
- Make tests pass
- Add Windows runs to azure yml
Issue: #2

Add Windows to run Unit tests

---

CHANGES.md
README.md
setup.py

Summary:
- Also add a line to state we run and test on Linux, MacOS + Windows to README.md
Test Plan:
- CI

Update Documentation for new 2019.3.5 version

---

.travis.yml
README.md
ci.py
ptr.py
ptr_tests.py
ptr_tests_fixtures.py
ptrconfig.sample
setup.cfg.sample
setup.py

- Add `pyre-check` as a dep
- Add in a step + the command generation for pyre
- Fix + add tests
Test: CI passes now with running `pyre`
Fixes #40

Add the ability to run Facebook's pyre type checker

---

ptr.py
ptr_tests.py

- Swap bool clowntown around
- Fix up other lint and typing errors
Unit tests passed this correctly and test running still worked with unit testing.

Fix bad bool passing for --print-cov + --error-on-warnings

---

ptr.py
ptr_tests.py
ptr_tests_fixtures.py

Summary:
- Update function + tests to expect a fail result for a non existent file requiring coverage
- Fix a bug and pass runtime
- Mock time() for tests to be consistent
Test Plan:
Added unit tests to expect the new correct return
Issue: #64

Fail when a non existent file has required coverage

---

.github/workflows/pythonpackage.yml
README.md
ptr.py

- Don't install `requirements.txt`
- Update setuptools + pip each run
- Set pythonioencoding env var for Windows
Fixes #61

Fix actions config

---

ptr.py
ptr_tests.py

Default to native recursive file search for black and flake8

---

README.md
ptr.py

Realphabetize command line arguments and update README

---

ci.py
ptr.py
ptr_tests.py
ptr_tests_fixtures.py

- We no longer need python 3.5 which allows f-strings to be used everywhere
- f-string is faster

Move all .format() strs to f-string

---

CHANGES.md
README.md
ptr.py
ptr_tests.py
setup.py

- Pyre now works with 3.8
cc: @jimmylai

Enable pyre for 3.8 + Update version + CHANGES.md

---

CODE_OF_CONDUCT.md
README.md

Add updated links + content to comply with FB Standards.

Update COC + Link to Terms of use & Privacy Policy

---

ptr.py

- Update handling of `subprocess.returncode` if it is None
- i.e. default to -1

Update usage of subprocess.returncode to please typing

---

ptr_tests.py
ptr_tests_fixtures.py
setup.cfg.sample
setup.py

- Disable until we can workout a way to make it run
- Opened an issue to work with pyre team: https://github.com/facebook/pyre-check/issues/316

Disable pyre on ptr CI

---

.pyre_configuration
ptr_tests.py
ptr_tests_fixtures.py
setup.cfg.sample
setup.py

- add a minimal pyre config (no hard setting directories)
- Fix unittests expectations
- Replace a manual monkey patch with a Mock.patch() to remove a typing error
Fixes https://github.com/facebook/pyre-check/issues/316 for ptr

Restore pyre running

---

.github/workflows/ci.yml
.pyre_configuration
ptr_tests.py
ptr_tests_fixtures.py
setup.cfg.sample
setup.py

- Use newer GitHub action for Python
- Add 3.9 into test matrix

Move to pyhton@v2 GitHub + Test in Python 3.9

---

ptr.py
ptr_tests.py
ptr_tests_fixtures.py
setup.cfg.sample
setup.py

- We need to support floats as coverage can return floats
- Make function for cleaner % removal
Testing: Update tests to ensure it works
Addresses part of #107

Support Floats for required coverage

---

ptr.py
ptr_tests.py
ptr_tests_fixtures.py
setup.cfg.sample
setup.py

- Print coverage when we don't have "required_coverage" in project ptr config
Testing: Update tests
- Unfortunately down to 89% TOTAL coverage
Fixes #106

Add support to print coverage without configuration set

---

.github/workflows/ci.yml
.github/workflows/ci_latest.yml

- Lets see how we go with upcomming python releases
Test: CI passing
Fixes #105

Add Ubuntu CI to run 3.10-dev

---

.github/workflows/ci.yml
.github/workflows/ci_latest.yml
mypy.ini
ptr.py
ptr_tests.py
setup.py

- Add to main CI
- Try 3.11-dev
3.6 support will be killed next month with cpython support ending.

Add 3.10 as supported

---

.pylint
ptr.py
ptr_tests.py
ptr_tests_fixtures.py
setup.py

- Forgot to re-enable since no 3.9 support :O
- Convert all strings to f-strings
- Change max-statements to 100

Reactive pylint on CI + f-string all

---

.github/workflows/ci.yml
.github/workflows/ci_latest.yml
.github/workflows/fuzz.yml
.ptrconfig
.pylint
fuzz.py
ptr.py
ptr_tests_fixtures.py
requirements.txt
setup.cfg.sample
setup.py

- Move named_tuples to NamedTypes + typed
- Remove all type comments
- Generate some basic hypothesis tests
- The typing helped this
- Fixes to ptr.py
- use .get() to access stats defaulting to 0 if not created
- Add some extra checks for when dirs don't exist and falsey values
- Seems an exclude pattern of '.' is bad, so exclude it and log so
- Add GitHub Fuzz action to run

Add Hypothesis Fuzzing + more typing + small fixes

---

.github/workflows/ci_latest.yml
.pylint
fuzz.py
ptr.py
ptr_tests.py
ptr_tests_fixtures.py
pyproject.toml
setup.cfg.sample
setup.py

- pylint supports 3.11 so lets test it again
- Lets pull in latest default config + relint everything
- Lots and lots of fixes
Make unittests pass locally ...
- `/tmp/tp/bin/coverage run ptr_tests.py`
Run ptr on itself
- `/tmp/tp/bin/ptr --print-cov --run-disabled -k`

Readd pylint on CI
